---
apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterCatalog
metadata:
  name: catalogd-openshift-community-operators
spec:
  source:
    image:
      pollInterval: 10m0s
      ref: registry.redhat.io/redhat/community-operator-index:v4.18
    type: Image
